version: "4.2"
services:

  ingress:
    build: 
      context : ingress
    #image: livekit/ingress:latest
    environment:
      INGRESS_CONFIG_BODY : |
            redis:
              address: 192.168.1.148:6379
              db: 0
            api_key: devkey
            api_secret: secret
            ws_url: ws://docker-container-backend-1:7880
            log_level: debug
            rtmp_port: 1935
            http_relay_port: 9090
            cpu_cost:
              rtmp_cpu_cost: 2.0
            
    ports:
    - target: 1935
      host_ip: 127.0.0.1
      # host_ip: 172.20.0.3
      published: 1935
      protocol: tcp
      


  backend:
    build: 
      context: livekit
    environment:
      LIVEKIT_CONFIG: |
          port: 7880
          log_level: debug
          redis:
            address: 192.168.1.148:6379
            db: 0
          rtc:
            tcp_port: 7881
            port_range_start: 50000
            port_range_end: 60000
            use_external_ip: false
            node_ip: 127.0.0.1
            udp_port: 7882
          keys:
            devkey: secret
          turn:
            enabled: false
          bind_addresses: [0.0.0.0]
          ingress:
              rtmp_base_url: "rtmp://localhost:1935"
          development: true
    ports:
    - target: 7880
      host_ip: 127.0.0.1
      # host_ip: 172.20.0.2
      published: 7880
      protocol: tcp
      mode: host



  